### ISSUE TITLE
Error compiling example

### ISSUE THREAD

**Issue by patrick-dojofive** [miko007/SerialTerminal#3]
```
in file included from /var/folders/0q/kx24shts5396rqt4r2rgpkfr0000gn/T/arduino_modified_sketch_951870/calculator.ino:1:0:
/Users/patricklittle/Documents/Arduino/libraries/SerialTerminalPRO-1.1.1/SerialTerminal.hpp: In static member function 'static maschinendeck::Pair<String, String> maschinendeck::SerialTerminal::ParseCommand(String)':
/Users/patricklittle/Documents/Arduino/libraries/SerialTerminalPRO-1.1.1/SerialTerminal.hpp:174:26: error: 'begin' was not declared in this scope
         for (auto& car : message) {
                          ^
/Users/patricklittle/Documents/Arduino/libraries/SerialTerminalPRO-1.1.1/SerialTerminal.hpp:174:26: note: suggested alternative:
In file included from /Applications/Teensyduino.app/Contents/Java/hardware/tools/arm/arm-none-eabi/include/c++/5.4.1/utility:75:0,
                 from /Applications/Teensyduino.app/Contents/Java/hardware/teensy/avr/cores/teensy3/wiring.h:89,
                 from /Applications/Teensyduino.app/Contents/Java/hardware/teensy/avr/cores/teensy3/WProgram.h:45,
                 from /var/folders/0q/kx24shts5396rqt4r2rgpkfr0000gn/T/arduino_build_36158/pch/Arduino.h:6:
/Applications/Teensyduino.app/Contents/Java/hardware/tools/arm/arm-none-eabi/include/c++/5.4.1/initializer_list:89:5: note:   'std::begin'
     begin(initializer_list<_Tp> __ils) noexcept
     ^
In file included from /var/folders/0q/kx24shts5396rqt4r2rgpkfr0000gn/T/arduino_modified_sketch_951870/calculator.ino:1:0:
/Users/patricklittle/Documents/Arduino/libraries/SerialTerminalPRO-1.1.1/SerialTerminal.hpp:174:26: error: 'end' was not declared in this scope
         for (auto& car : message) {
                          ^
/Users/patricklittle/Documents/Arduino/libraries/SerialTerminalPRO-1.1.1/SerialTerminal.hpp:174:26: note: suggested alternative:
In file included from /Applications/Teensyduino.app/Contents/Java/hardware/tools/arm/arm-none-eabi/include/c++/5.4.1/utility:75:0,
                 from /Applications/Teensyduino.app/Contents/Java/hardware/teensy/avr/cores/teensy3/wiring.h:89,
                 from /Applications/Teensyduino.app/Contents/Java/hardware/teensy/avr/cores/teensy3/WProgram.h:45,
                 from /var/folders/0q/kx24shts5396rqt4r2rgpkfr0000gn/T/arduino_build_36158/pch/Arduino.h:6:
/Applications/Teensyduino.app/Contents/Java/hardware/tools/arm/arm-none-eabi/include/c++/5.4.1/initializer_list:99:5: note:   'std::end'
     end(initializer_list<_Tp> __ils) noexcept
     ^
Using library SerialTerminalPRO-1.1.1 at version 1.1.1
```

**Comment by miko007** [comment]
Hello!

first, it would have been nice if you put the output into code tags, i did that for you.

second, i am pretty shure, this has something to do with the *Teensyduino.app* you are using. This library has only ever been tested using the original *Arduino IDE* and real Arduino boards *(and, thanks to #2, on the ESP-type boards)*.

The library uses a range-based-for-loop to iterate over the Arduino bultin type `String`, which in your case does not seem to implement the nessecary iterators to be used in such a loop, and thus, seems to differ from the standard Arduino type `String` and fails to compile.

I have downloaded the *Teensyduino.app* and tried to compile this simple program, that also failed:

```c++
void setup() {
	String foo = "Hello";
	for (auto& car : foo) {
		Serial.print(car);	
	}

}
```

so this is pretty much an issue with the `Arduino.h` of your *Teensyduino* app and the compiler version seems a bit out of date. I can not really provide any help other than suggesting that you fork this library an rewrite the loop at the end of `SerialTerminal.hpp` to something like:

```c++
            static Pair<String, String> ParseCommand(String& message) {
                String keyword = "";
                for (size_t i = 0; i < message.length(); i++) {
		   char car = message[i];
                    if (car == ' ')
                        break;
                    keyword += car;
                }
                if (keyword != "")
                    message.remove(0, keyword.length());
                keyword.trim();
                message.trim();

                return Pair<String, String>(move(keyword), move(message));
            }
```

this library is developed to use as much modern c++ as possible and all the newest language features, so i won't change this just because it does not run "as is" on a non-Arduino board in another IDE, sorry.

I hope i could help you to some extend, anyways.

**Comment by patrick-dojofive** [comment]
Sorry, and thank you.
Unfortunately, this work is for a client and we'll be using the Teensyduino app and I need the library manager to bring in any library code.
I'll get in touch with PJRC and try to see why their `Arduino.h` is different. I was under the impression that their duino app was just OTS Arduino with their libraries slipstreamed into the contents.

**Comment by miko007** [comment]
> libraries slipstreamed into the contents

Thats basically what's inside `Arduino.h`. This "standard library" has to be ported to each platform. It looks like the implementation for the *teensy* platform is a bit different, which is often the case tbh *(i.e. on the esp platform you get the full fledged c++ STL, on Arduino you do not)*.

I would even offer to make the offending method `virtual`, so you could override it, but unfortunately this is not possible in c++, as `maschinendeck::SerialTerminal::ParseCommand()` is a static method.

I could also do my own implementation of `String`, but that would make the library much bigger, would not play nice with other Arduino code and it way out of scope for this, i guess.

If the implementation of `String` differs from the standard Arduino one, we can not even guarantee, that there will not be unreasonable memory allocation, or which effect my `move()` method has on them. So it is not even "just change that one line of code" i fear.

**Comment by FrankBoesing** [comment]
Is that sufficient, or is something missing?

**Comment by miko007** [comment]
@FrankBoesing oh, this is interesting, so they just forgot to add the iterators when cpp11 arrived?

at first glance this will resolve @patrick-dojofive's problem. i was able compile the example with warnings using *Teensyduino.app* and `teensy 4.0` as the platform.

**Comment by FrankBoesing** [comment]
Looks like it was just forgotten.  
Your short example does not only compile, it works now.

**Comment by miko007** [comment]
well, thank you very much @FrankBoesing for helping out! we could not have figured that out without you, as @patrick-dojofive does not seem familiar with Arduino and compile intrinsics and i myself never programmed for a teensy.

**Comment by patrick-dojofive** [comment]
Good work guys. This is my first time using Arduino, but I've been programming embedded devices for 15 years. 
I'm familiar with intrinsics, but I've always had the luxury of treating them as golden tools in the toolbox.
