### ISSUE TITLE
Inverted precompile

### ISSUE THREAD

**Issue by patrick-dojofive** [miko007/SerialTerminal#4]
In your header file you have the following code
```c
  #if not defined ST_FLAG_NOBUILTIN && defined E2END
  #include "EEPROM.h"
```
The problem is that the first line cannot resolve to be true unless EEPROM.h has already been included as it defines E2END.

A workaround is to include EEPROM.h from the user sketch before including SerialTerminal.hpp.

A possible fix in code would be
```c
  #if not defined ST_FLAG_NOBUILIN
  #include "EEPROM.h"
  #if defined E2END
```
You could also just trade the two original lines around, but I'm not sure if that would have unintended side-effects.

**Comment by miko007** [comment]
i am currently on vacation. i will have a look in about two weeks.

**Comment by miko007** [comment]
the two weeks went a bit longer, didn't they? totally forgot about this.

i however deem this claim to not be true, as the `E2END` macro is defined in `avr/io.h`, according to the documentation:

https://github.com/coolya/mbeddr.arduino/blob/master/include/avr/io.h

i will close this for now, feel free to keep the conversation going, if i have overlooked something.

**Comment by patrick-dojofive** [comment]
If memory serves me correctly, I was trying to use your library with the Arduino compatible Teensy 4.1 from pjrc.com.
I believe that I needed to apply my described patch in order for it to compile.
However, I no longer have access to that project so I can't easily provide more details.
